#!/bin/bash
# 触发 Vercel 重新部署的脚本

echo "🚀 触发 Vercel 重新部署..."
echo ""
echo "由于 GitHub 权限限制，请使用以下方法之一："
echo ""
echo "方法1：在 Vercel Dashboard 手动触发"
echo "  1. 打开 https://vercel.com/dashboard"
echo "  2. 点击 xhs-generator 项目"
echo "  3. 点击 Deployments 标签"
echo "  4. 找到最新部署，点击右侧 '···' → 'Redeploy'"
echo ""
echo "方法2：通过 GitHub 网页编辑文件"
echo "  1. 打开 https://github.com/ericlau0305hk/xhs-generator"
echo "  2. 随便编辑一个文件（如 README.md）"
echo "  3. 添加一个空格或换行"
echo "  4. 点击 'Commit changes'"
echo "  5. Vercel 会自动检测到变化并重新部署"
echo ""
echo "方法3：配置 Git 凭证后推送"
echo "  1. 确保你已登录 GitHub（浏览器中）"
echo "  2. 执行: git config --global credential.helper osxkeychain"
echo "  3. 再次尝试: git push origin main"
echo "  4. 浏览器会弹窗授权"
echo ""
